### ISSUE TITLE
While call start payment i got this error

### ISSUE THREAD

**Issue by madhanapk** [isathyam/CordovaPayTM#1]

**Comment by madhanapk** [comment]
W/System.err(14304): java.lang.SecurityException: ConnectivityService: Neither user 10130 nor curren
t process has android.permission.ACCESS_NETWORK_STATE.
W/System.err(14304):    at android.os.Parcel.readException(Parcel.java:1472)
W/System.err(14304):    at android.os.Parcel.readException(Parcel.java:1426)
W/System.err(14304):    at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnect
ivityManager.java:830)
W/System.err(14304):    at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.
java:621)
W/System.err(14304):    at com.paytm.pgsdk.PaytmUtility.isNetworkAvailable(PaytmUtility.java:128)
W/System.err(14304):    at com.paytm.pgsdk.PaytmPGService.startPaymentTransaction(PaytmPGService.jav
a:180)
W/System.err(14304):    at com.paytm.cordova.PayTM.startPayment(PayTM.java:91)
W/System.err(14304):    at com.paytm.cordova.PayTM.execute(PayTM.java:51)
W/System.err(14304):    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
W/System.err(14304):    at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
W/System.err(14304):    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err(14304):    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java
:41)
W/System.err(14304):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Na
tive Method)
W/System.err(14304):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMe
ssageHandler.java:27)
W/System.err(14304):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(14304):    at android.os.Looper.loop(Looper.java:149)
W/System.err(14304):    at android.os.HandlerThread.run(HandlerThread.java:61)
